eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign

logging:
  level:
    com.netflix.loadbalancer.LoadBalancerContext: DEBUG
    com.forezp.service.SchedualServiceHi: DEBUG

serv_url:
  reg: http://127.0.0.1:8764